package edu.neu.zhiyao.assignment2.server.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;

/**
 *
 * Simple class to wrap the data in a RFId lift pass reader record
 */
@DynamoDBTable(tableName = "RFIDLift")
public class RFIDLiftData implements Serializable, Comparable<RFIDLiftData>  {
    
    private String id;
    private int resortId;
    private int dayNum;
    private int skierId;
    private int liftId;
    private int time;

    public RFIDLiftData() {
        
    }
    
    public RFIDLiftData(int resortId, int dayNum, int skierId, int liftId, int time) {
        this.resortId = resortId;
        this.dayNum = dayNum;
        this.skierId = skierId;
        this.liftId = liftId;
        this.time = time;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @DynamoDBAttribute(attributeName = "ResortId")
    public int getResortId() {
        return resortId;
    }

    public void setResortId(int resortId) {
        this.resortId = resortId;
    }

    @DynamoDBAttribute(attributeName = "DayNum")
    public int getDayNum() {
        return dayNum;
    }

    public void setDayNum(int dayNum) {
        this.dayNum = dayNum;
    }

    @DynamoDBRangeKey(attributeName = "SkierId")
    public int getSkierId() {
        return skierId;
    }

    public void setSkierId(int skierId) {
        this.skierId = skierId;
    }

    @DynamoDBAttribute(attributeName = "LiftId")
    public int getLiftId() {
        return liftId;
    }

    public void setLiftId(int liftId) {
        this.liftId = liftId;
    }

    @DynamoDBAttribute(attributeName = "Time")
    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }
   
    @Override
    public int compareTo(RFIDLiftData compareData) {
        int compareTime = ((RFIDLiftData) compareData).getTime();
        
        //ascending order
        return this.time - compareTime ;
    }
    
}
